name: job
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-image
  - matplotlib
  - opencv
  - pillow
  - imageio
  - tifffile
  - pytorch=2.4
  - torchvision=0.19
  - torchaudio=2.4
  - pytorch-cuda=12.1
  - tqdm
  - pyyaml
  - requests
  - tensorboard
  - opt_einsum
  - p7zip
  - pip:
      - ninja
      - absl-py
      - future
      - protobuf
      - cloudpickle
      - fsspec
      - setuptools
      - wheel
      - accelerate
      - einops
      - fastapi
      - gradio
      - huggingface-hub
      - ipython
      - matplotlib-inline
      - omegaconf
      - pydantic
      - scikit-learn
      - transformers
      - uvicorn
      - wandb
